<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">
    <text>Fast Export</text>

    <Action name="fastExport">
      <icon></icon>
      <text>Fast Export</text>
      <whatsThis></whatsThis>
      <toolTip>Export To PNG file with directory remembered</toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
